version: 2
jobs:

  lint:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-v8-{{ checksum "package.json" }}
          - dependencies-v8
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-v8-{{ checksum "package.json" }}
      - run: npm run lint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
